#!/usr/bin/env python3
# setup_course.py
# Interactive setup script for Canvas course credentials

import os
import sys
import subprocess

def ensure_venv():
    root_dir = os.path.dirname(os.path.abspath(__file__))
    venv_dir = os.path.join(root_dir, 'venv')
    venv_python = os.path.join(venv_dir, 'bin', 'python')
    if os.name == 'nt':
        venv_python = os.path.join(venv_dir, 'Scripts', 'python.exe')
        
    # Check if we are running from the venv
    if os.path.abspath(sys.executable) != os.path.abspath(venv_python):
        print("=> Ensuring virtual environment exists...")
        if not os.path.exists(venv_dir):
            subprocess.check_call([sys.executable, "-m", "venv", "venv"])
        
        print("=> Installing/Updating dependencies...")
        subprocess.check_call([venv_python, "-m", "pip", "install", "-r", "requirements.txt", "--quiet"])
        
        print("=> Restarting setup inside virtual environment...\n")
        os.execv(venv_python, [venv_python] + sys.argv)

def main():
    ensure_venv()
    print("=========================================")
    print(" Canvas Scripts - Course Setup Onboarding")
    print("=========================================\n")
    print("This script will help you configure your local course credentials.")
    print("It will generate the '_credentials.py' file required by the other scripts.\n")

    # 1. Path
    # Auto-detect root dir (assuming this script is in canvas_scripts/)
    root_dir = os.path.dirname(os.path.abspath(__file__)) + '/'
    
    print("1. Local Course Path")
    print(f"We detected your course folder as: {root_dir}")
    my_path = input("Press Enter to accept this, or type the full path: ").strip()
    if not my_path:
        my_path = root_dir
    if not my_path.endswith('/'):
        my_path += '/'

    # 2. API_URL
    print("\n2. Canvas API URL")
    print("This is the base URL you use to log in to Canvas.")
    print("Example: https://example.instructure.com")
    api_url = input("API URL: ").strip()
    api_url = api_url.rstrip('/')

    # 3. API_KEY
    print("\n3. Canvas API Key")
    print("Go to your Canvas profile Settings -> 'New Access Token' to generate this.")
    api_key = input("API Key: ").strip()

    # 4. COURSE_NUM
    print("\n4. Course Number")
    print("Go to your Canvas course home page. The course number is the number in the URL after /courses/")
    print("Example: For https://example.instructure.com/courses/123456, enter 123456")
    course_num_input = input("Course Number: ").strip()
    while not course_num_input.isdigit():
        print("Please enter digits only.")
        course_num_input = input("Course Number: ").strip()
    
    course_num = int(course_num_input)

    print("\nAttempting to connect to Canvas and verify credentials...")
    user_id = None
    
    try:
        from canvasapi import Canvas
        canvas = Canvas(api_url, api_key)
        
        # Verify course
        course = canvas.get_course(course_num)
        print(f"  [+] Successfully connected to Course: {course.name}")
        
        # Get user ID
        current_user = canvas.get_current_user()
        user_id = current_user.id
        print(f"  [+] Successfully verified User: {current_user.name} (ID: {user_id})")
        
    except ImportError:
        print("\nWARNING: canvasapi module is not installed. Please run 'python3 -m pip install -r requirements.txt'")
        print("We will save your credentials without verification.")
    except Exception as e:
        print(f"\nFailed to verify connection to Canvas: {e}")
        print("Please double check your API URL, Key, and Course Number.")
        choice = input("Do you want to save these credentials anyway? (y/n): ")
        if choice.lower() != 'y':
            print("Exiting without saving.")
            sys.exit(1)

    if user_id is None:
        user_id = "123456 # Verify failed or canvasapi missing. Replace manually or run api_get_user_id.py later"

    # Write to _credentials.py
    cred_file = os.path.join(root_dir, 'scripts', '_credentials.py')
    
    print(f"\nWriting credentials to {cred_file}...")
    try:
        with open(cred_file, 'w', encoding='utf-8') as f:
            f.write("#!/usr/bin/env python3\n")
            f.write("# _credentials.py\n")
            f.write("# Generated by setup_course.py\n\n")
            f.write(f'MY_PATH = "{my_path}"\n')
            f.write('MY_PAGES = MY_PATH + "pages/"\n')
            f.write('MY_ANNOUNCEMENTS = MY_PATH + "announcements/"\n')
            f.write('MY_DISCUSSIONS = MY_PATH + "discussions/"\n')
            f.write('MY_ASSIGNMENTS = MY_PATH + "assignments/"\n\n')
            f.write(f'API_URL = "{api_url}"\n')
            f.write(f'API_KEY = "{api_key}"\n')
            f.write(f'COURSE_NUM = {course_num}\n')
            f.write(f'USER_ID = {user_id}\n')
        
        print("Success! You are all set.")
        print("You can now use the other scripts in this repository.")
    except Exception as e:
        print(f"Failed to write to file: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
